#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
#  Phira MP 联机服务器一键安装脚本 for Termux
#  版本: 2.2.0
#  作者: RiLuo-ya
# ============================================================
set -e
# ==================== 颜色定义 ====================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color
# ==================== 全局变量 ====================
TOTAL_STEPS=7
CURRENT_STEP=0
INSTALL_DIR="$HOME/tphira-mp"
MAIN_SH_URL="https://raw.githubusercontent.com/riluo-ya/blog/main/sh/Phira-mp/main.sh"
# ==================== 工具函数 ====================
# 打印横幅
print_banner() {
    clear
    echo -e "${PURPLE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                                                              ║"
    echo "║   ██████╗ ██╗  ██╗██╗██████╗  █████╗     ███╗   ███╗██████╗  ║"
    echo "║   ██╔══██╗██║  ██║██║██╔══██╗██╔══██╗    ████╗ ████║██╔══██╗ ║"
    echo "║   ██████╔╝███████║██║██████╔╝███████║    ██╔████╔██║██████╔╝ ║"
    echo "║   ██╔═══╝ ██╔══██║██║██╔══██╗██╔══██║    ██║╚██╔╝██║██╔═══╝  ║"
    echo "║   ██║     ██║  ██║██║██║  ██║██║  ██║    ██║ ╚═╝ ██║██║      ║"
    echo "║   ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═╝    ╚═╝     ╚═╝╚═╝      ║"
    echo "║                                                              ║"
    echo "║            Phira 联机服务器 - 一键安装脚本                    ║"
    echo "║                    for Termux                                ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
}
# 进度条
show_progress() {
    local current=$1
    local total=$2
    local title=$3
    local percent=$(( current * 100 / total ))
    local filled=$(( percent / 2 ))
    local empty=$(( 50 - filled ))
    
    echo -e "${CYAN}【步骤 ${current}/${total}】${NC} ${WHITE}${title}${NC}"
    echo -ne "${GREEN}["
    printf "%0.s█" $(seq 1 $filled)
    printf "%0.s░" $(seq 1 $empty)
    echo -e "] ${percent}%${NC}"
    echo ""
}
# 成功消息
print_success() {
    echo -e "${GREEN}✅ ${1}${NC}"
    echo ""
}
# 信息消息
print_info() {
    echo -e "${BLUE}ℹ️  ${1}${NC}"
}
# 警告消息
print_warning() {
    echo -e "${YELLOW}⚠️  ${1}${NC}"
}
# 错误消息
print_error() {
    echo -e "${RED}❌ ${1}${NC}"
}
# 配置 .bashrc 自动启动（直接写入逻辑）
configure_bashrc() {
    local bashrc_path="$HOME/.bashrc"
    local marker="# Phira MP Auto Start - Generated by install script"
    
    # 检查是否已配置，已配置则先删除旧配置
    if grep -q "Phira MP Auto Start" "$bashrc_path" 2>/dev/null; then
        # 删除旧的配置块
        sed -i '/# Phira MP Auto Start/,/^# Phira MP Auto End/d' "$bashrc_path" 2>/dev/null || true
    fi
    
    # 写入完整的检测和下载逻辑到 .bashrc - 只使用 GitHub 直连
    cat >> "$bashrc_path" << 'BASHRC_EOF'
# Phira MP Auto Start - Generated by install script
# 自动检测 main.sh，不存在则从 GitHub 下载
if [ -z "$PHIRA_MP_STARTED" ]; then
    export PHIRA_MP_STARTED=1
    
    MAIN_SH_PATH="$HOME/main.sh"
    MAIN_SH_URL="https://raw.githubusercontent.com/riluo-ya/blog/main/sh/Phira-mp/main.sh"
    
    # 检查 main.sh 是否存在，不存在则从 GitHub 下载
    if [ ! -f "$MAIN_SH_PATH" ]; then
        echo -e "\033[0;34m═══════════════════════════════════════════════\033[0m"
        echo -e "\033[0;32m  Phira MP 启动器\033[0m"
        echo -e "\033[0;34m═══════════════════════════════════════════════\033[0m"
        echo ""
        echo -e "\033[1;33m! 未检测到 main.sh，正在从 GitHub 下载...\033[0m"
        echo ""
        echo -e "\033[1;33m   → 下载地址: ${MAIN_SH_URL}\033[0m"
        
        if curl -s -L --connect-timeout 15 --max-time 60 "$MAIN_SH_URL" -o "$MAIN_SH_PATH" 2>/dev/null; then
            if [ -s "$MAIN_SH_PATH" ]; then
                chmod +x "$MAIN_SH_PATH"
                echo -e "   \033[0;32m✓ 下载成功\033[0m"
            else
                echo -e "   \033[0;31m✗ 下载失败，文件为空\033[0m"
                rm -f "$MAIN_SH_PATH"
            fi
        else
            echo -e "   \033[0;31m✗ 下载失败，请检查网络连接\033[0m"
        fi
        echo ""
    fi
    
    # 执行 main.sh
    if [ -f "$MAIN_SH_PATH" ]; then
        chmod +x "$MAIN_SH_PATH"
        cd "$HOME"
        bash "$MAIN_SH_PATH"
    fi
fi
# Phira MP Auto End
BASHRC_EOF
    echo -e "   ${GREEN}✓ .bashrc 已配置自动启动${NC}"
}
# ==================== 主安装流程 ====================
main() {
    print_banner
    
    echo -e "${YELLOW}即将开始安装 Phira MP 联机服务器${NC}"
    echo -e "${YELLOW}安装目录: ${INSTALL_DIR}${NC}"
    echo ""
    read -p "按 Enter 键开始安装，或按 Ctrl+C 取消..."
    echo ""
    
    # ==================================================
    # 步骤 1: 更新软件源
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "更新软件源"
    
    print_info "正在更新 pkg 软件源并升级系统包..."
    echo ""
    
    pkg update -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
    pkg upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
    
    print_success "软件源更新完成"
    sleep 1
    
    # ==================================================
    # 步骤 2: 安装依赖
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "安装 Node.js, Git, curl 等依赖"
    
    print_info "正在安装 Node.js (LTS 版本)..."
    pkg install -y nodejs-lts
    
    print_info "正在安装 Git..."
    pkg install -y git
    
    print_info "正在安装 curl..."
    pkg install -y curl
    
    print_info "正在安装 pnpm 包管理器..."
    npm install -g pnpm
    
    echo ""
    print_success "依赖安装完成"
    echo -e "   Node.js 版本: $(node -v)"
    echo -e "   pnpm 版本: $(pnpm -v)"
    echo -e "   Git 版本: $(git --version | awk '{print $3}')"
    sleep 1.5
    
    # ==================================================
    # 步骤 3: 克隆项目
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "克隆联机服务器项目"
    
    if [ -d "$INSTALL_DIR" ]; then
        print_warning "检测到已存在的项目目录，正在删除..."
        rm -rf "$INSTALL_DIR"
    fi
    
    print_info "正在从 GitHub 克隆项目..."
    git clone https://github.com/Pimeng/tphira-mp.git "$INSTALL_DIR"
    
    cd "$INSTALL_DIR"
    print_success "项目克隆完成，当前目录: $(pwd)"
    sleep 1
    
    # ==================================================
    # 步骤 4: 配置文件准备
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "准备配置文件"
    
    print_info "正在复制配置文件..."
    cp server_config.example.yml server_config.yml
    
    print_success "配置文件已创建: server_config.yml"
    sleep 0.5
    
    # ==================================================
    # 步骤 5: 安装项目依赖并构建
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "安装项目依赖并构建"
    
    print_info "正在安装项目依赖 (这可能需要几分钟)..."
    pnpm install
    
    print_info "正在构建项目..."
    pnpm run build
    
    print_success "项目构建完成"
    sleep 1
    
    # ==================================================
    # 步骤 6: 修补语言文件 l10n.ts
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "修补语言系统文件"
    
    print_info "正在修补 src/server/utils/l10n.ts..."
    
    cat > src/server/utils/l10n.ts << 'EOF'
import { FluentBundle, FluentResource } from "@fluent/bundle";
import { negotiateLanguages } from "@fluent/langneg";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { getAppPaths } from "../utils/appPaths.js";
const SUPPORTED_LANGS = ["en-US", "zh-CN", "zh-TW", "ja-JP", "ko-KR", "ru-RU"];
function loadBundle(lang) {
    const bundle = new FluentBundle(lang, { useIsolating: false });
    const path = join(getAppPaths().localesDir, `${lang}.ftl`);
    const source = readFileSync(path, "utf8");
    bundle.addResource(new FluentResource(source));
    return bundle;
}
const bundles = Object.fromEntries(SUPPORTED_LANGS.map((lang) => [lang, loadBundle(lang)]));
export class Language {
    lang;
    constructor(lang) {
        const normalized = normalizeLocaleHint(lang);
        const resolved = negotiateLanguages([normalized], SUPPORTED_LANGS, { defaultLocale: "zh-CN" });
        this.lang = resolved[0] ?? "zh-CN";
    }
    format(key, args) {
        const bundle = bundles[this.lang];
        const msg = bundle.getMessage(key);
        if (!msg || !msg.value) {
            throw new Error(`缺少翻译：${key}（lang=${this.lang}）`);
        }
        // 修复 who/user 变量不一致的 bug
        const fixedArgs = args ? { ...args } : {};
        if (fixedArgs.who !== undefined && fixedArgs.user === undefined) {
            fixedArgs.user = fixedArgs.who;
        }
        if (fixedArgs.user !== undefined && fixedArgs.who === undefined) {
            fixedArgs.who = fixedArgs.user;
        }
        return bundle.formatPattern(msg.value, fixedArgs, null);
    }
}
function normalizeLocaleHint(hint) {
    const trimmed = hint.trim();
    if (!trimmed)
        return "";
    const base = trimmed.split(/[.@]/, 1)[0] ?? trimmed;
    return base.replace(/_/g, "-");
}
export function tl(lang, key, args) {
    return lang.format(key, args);
}
EOF
    
    print_success "l10n.ts 文件修补完成（已修复 who/user 变量不一致问题）"
    sleep 0.5
    
    # ==================================================
    # 步骤 7: 配置 .bashrc 自动启动
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "配置 .bashrc 自动启动"
    
    print_info "正在写入自动启动逻辑到 .bashrc..."
    echo ""
    
    # 直接配置 .bashrc（不生成中间脚本，只使用 GitHub 直连）
    configure_bashrc
    
    echo ""
    print_success ".bashrc 自动启动配置完成"
    sleep 0.5
    
    # ==================================================
    # 安装完成
    # ==================================================
    clear
    echo -e "${GREEN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                                                              ║"
    echo "║                    🎉  安装成功！ 🎉                         ║"
    echo "║                                                              ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    echo -e "${GREEN}  Phira MP 联机服务器已安装完成！${NC}"
    echo ""
    echo -e "${CYAN}  下次打开 Termux 时将自动检测并启动！${NC}"
    echo ""
}
# 错误处理
trap 'echo ""; print_error "安装过程中出现错误，请检查上面的输出信息"; exit 1' ERR
# 启动主程序
main
