#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
#  Phira MP 联机服务器一键安装脚本 for Termux
#  版本: 2.2.0
#  作者: RiLuo-ya
# ============================================================

set -e

# ==================== 颜色定义 ====================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

# ==================== 全局变量 ====================
TOTAL_STEPS=8
CURRENT_STEP=0
INSTALL_DIR="$HOME/tphira-mp"
MAIN_SH_URL="https://raw.githubusercontent.com/riluo-ya/blog/main/sh/Phira-mp/main.sh"

# ==================== 工具函数 ====================

# 打印横幅
print_banner() {
    clear
    echo -e "${PURPLE}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                                                              ║"
    echo "║   ██████╗ ██╗  ██╗██╗██████╗  █████╗     ███╗   ███╗██████╗  ║"
    echo "║   ██╔══██╗██║  ██║██║██╔══██╗██╔══██╗    ████╗ ████║██╔══██╗ ║"
    echo "║   ██████╔╝███████║██║██████╔╝███████║    ██╔████╔██║██████╔╝ ║"
    echo "║   ██╔═══╝ ██╔══██║██║██╔══██╗██╔══██║    ██║╚██╔╝██║██╔═══╝  ║"
    echo "║   ██║     ██║  ██║██║██║  ██║██║  ██║    ██║ ╚═╝ ██║██║      ║"
    echo "║   ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═╝  ╚═╝    ╚═╝     ╚═╝╚═╝      ║"
    echo "║                                                              ║"
    echo "║            Phira 联机服务器 - 一键安装脚本                    ║"
    echo "║                    for Termux                                ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
}

# 进度条
show_progress() {
    local current=$1
    local total=$2
    local title=$3
    local percent=$(( current * 100 / total ))
    local filled=$(( percent / 2 ))
    local empty=$(( 50 - filled ))
    
    echo -e "${CYAN}【步骤 ${current}/${total}】${NC} ${WHITE}${title}${NC}"
    echo -ne "${GREEN}["
    printf "%0.s█" $(seq 1 $filled)
    printf "%0.s░" $(seq 1 $empty)
    echo -e "] ${percent}%${NC}"
    echo ""
}

# 成功消息
print_success() {
    echo -e "${GREEN}✅ ${1}${NC}"
    echo ""
}

# 信息消息
print_info() {
    echo -e "${BLUE}ℹ️  ${1}${NC}"
}

# 警告消息
print_warning() {
    echo -e "${YELLOW}⚠️  ${1}${NC}"
}

# 错误消息
print_error() {
    echo -e "${RED}❌ ${1}${NC}"
}

# 配置 .bashrc 自动启动（直接写入逻辑）
configure_bashrc() {
    local bashrc_path="$HOME/.bashrc"
    local marker="# Phira MP Auto Start - Generated by install script"
    
    # 检查是否已配置，已配置则先删除旧配置
    if grep -q "Phira MP Auto Start" "$bashrc_path" 2>/dev/null; then
        # 删除旧的配置块
        sed -i '/# Phira MP Auto Start/,/^# Phira MP Auto End/d' "$bashrc_path" 2>/dev/null || true
    fi
    
    # 写入完整的检测和下载逻辑到 .bashrc - 只使用 GitHub 直连
    cat >> "$bashrc_path" << 'BASHRC_EOF'

# Phira MP Auto Start - Generated by install script
# 自动检测 main.sh，不存在则从 GitHub 下载
if [ -z "$PHIRA_MP_STARTED" ]; then
    export PHIRA_MP_STARTED=1
    
    MAIN_SH_PATH="$HOME/main.sh"
    MAIN_SH_URL="https://raw.githubusercontent.com/riluo-ya/blog/main/sh/Phira-mp/main.sh"
    
    # 检查 main.sh 是否存在，不存在则从 GitHub 下载
    if [ ! -f "$MAIN_SH_PATH" ]; then
        echo -e "\033[0;34m═══════════════════════════════════════════════\033[0m"
        echo -e "\033[0;32m  Phira MP 启动器\033[0m"
        echo -e "\033[0;34m═══════════════════════════════════════════════\033[0m"
        echo ""
        echo -e "\033[1;33m! 未检测到 main.sh，正在从 GitHub 下载...\033[0m"
        echo ""
        echo -e "\033[1;33m   → 下载地址: ${MAIN_SH_URL}\033[0m"
        
        if curl -s -L --connect-timeout 15 --max-time 60 "$MAIN_SH_URL" -o "$MAIN_SH_PATH" 2>/dev/null; then
            if [ -s "$MAIN_SH_PATH" ]; then
                chmod +x "$MAIN_SH_PATH"
                echo -e "   \033[0;32m✓ 下载成功\033[0m"
            else
                echo -e "   \033[0;31m✗ 下载失败，文件为空\033[0m"
                rm -f "$MAIN_SH_PATH"
            fi
        else
            echo -e "   \033[0;31m✗ 下载失败，请检查网络连接\033[0m"
        fi
        echo ""
    fi
    
    # 执行 main.sh
    if [ -f "$MAIN_SH_PATH" ]; then
        chmod +x "$MAIN_SH_PATH"
        cd "$HOME"
        bash "$MAIN_SH_PATH"
    fi
fi
# Phira MP Auto End
BASHRC_EOF

    echo -e "   ${GREEN}✓ .bashrc 已配置自动启动${NC}"
}

# ==================== 主安装流程 ====================

main() {
    print_banner
    
    echo -e "${YELLOW}即将开始安装 Phira MP 联机服务器${NC}"
    echo -e "${YELLOW}安装目录: ${INSTALL_DIR}${NC}"
    echo ""
    read -p "按 Enter 键开始安装，或按 Ctrl+C 取消..."
    echo ""
    
    # ==================================================
    # 步骤 1: 更新软件源
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "更新软件源"
    
    print_info "正在更新 pkg 软件源并升级系统包..."
    echo ""
    
    pkg update -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
    pkg upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
    
    print_success "软件源更新完成"
    sleep 1
    
    # ==================================================
    # 步骤 2: 安装依赖
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "安装 Node.js, Git, curl 等依赖"
    
    print_info "正在安装 Node.js (LTS 版本)..."
    pkg install -y nodejs-lts
    
    print_info "正在安装 Git..."
    pkg install -y git
    
    print_info "正在安装 curl..."
    pkg install -y curl
    
    print_info "正在安装 pnpm 包管理器..."
    npm install -g pnpm
    
    echo ""
    print_success "依赖安装完成"
    echo -e "   Node.js 版本: $(node -v)"
    echo -e "   pnpm 版本: $(pnpm -v)"
    echo -e "   Git 版本: $(git --version | awk '{print $3}')"
    sleep 1.5
    
    # ==================================================
    # 步骤 3: 克隆项目
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "克隆联机服务器项目"
    
    if [ -d "$INSTALL_DIR" ]; then
        print_warning "检测到已存在的项目目录，正在删除..."
        rm -rf "$INSTALL_DIR"
    fi
    
    print_info "正在从 GitHub 克隆项目..."
    git clone https://github.com/Pimeng/tphira-mp.git "$INSTALL_DIR"
    
    cd "$INSTALL_DIR"
    print_success "项目克隆完成，当前目录: $(pwd)"
    sleep 1
    
    # ==================================================
    # 步骤 4: 配置文件准备
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "准备配置文件"
    
    print_info "正在复制配置文件..."
    cp server_config.example.yml server_config.yml
    
    print_success "配置文件已创建: server_config.yml"
    sleep 0.5
    
    # ==================================================
    # 步骤 5: 安装项目依赖并构建
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "安装项目依赖并构建"
    
    print_info "正在安装项目依赖 (这可能需要几分钟)..."
    pnpm install
    
    print_info "正在构建项目..."
    pnpm run build
    
    print_success "项目构建完成"
    sleep 1
    
    # ==================================================
    # 步骤 6: 修补语言文件 l10n.ts
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "修补语言系统文件"
    
    print_info "正在修补 src/server/utils/l10n.ts..."
    
    cat > src/server/utils/l10n.ts << 'EOF'
import { FluentBundle, FluentResource } from "@fluent/bundle";
import { negotiateLanguages } from "@fluent/langneg";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { getAppPaths } from "../utils/appPaths.js";

const SUPPORTED_LANGS = ["en-US", "zh-CN", "zh-TW", "ja-JP", "ko-KR", "ru-RU"];

function loadBundle(lang) {
    const bundle = new FluentBundle(lang, { useIsolating: false });
    const path = join(getAppPaths().localesDir, `${lang}.ftl`);
    const source = readFileSync(path, "utf8");
    bundle.addResource(new FluentResource(source));
    return bundle;
}

const bundles = Object.fromEntries(SUPPORTED_LANGS.map((lang) => [lang, loadBundle(lang)]));

export class Language {
    lang;

    constructor(lang) {
        const normalized = normalizeLocaleHint(lang);
        const resolved = negotiateLanguages([normalized], SUPPORTED_LANGS, { defaultLocale: "zh-CN" });
        this.lang = resolved[0] ?? "zh-CN";
    }

    format(key, args) {
        const bundle = bundles[this.lang];
        const msg = bundle.getMessage(key);
        if (!msg || !msg.value) {
            throw new Error(`缺少翻译：${key}（lang=${this.lang}）`);
        }

        // 修复 who/user 变量不一致的 bug
        const fixedArgs = args ? { ...args } : {};
        if (fixedArgs.who !== undefined && fixedArgs.user === undefined) {
            fixedArgs.user = fixedArgs.who;
        }
        if (fixedArgs.user !== undefined && fixedArgs.who === undefined) {
            fixedArgs.who = fixedArgs.user;
        }

        return bundle.formatPattern(msg.value, fixedArgs, null);
    }
}

function normalizeLocaleHint(hint) {
    const trimmed = hint.trim();
    if (!trimmed)
        return "";
    const base = trimmed.split(/[.@]/, 1)[0] ?? trimmed;
    return base.replace(/_/g, "-");
}

export function tl(lang, key, args) {
    return lang.format(key, args);
}
EOF
    
    print_success "l10n.ts 文件修补完成（已修复 who/user 变量不一致问题）"
    sleep 0.5
    
    # ==================================================
    # 步骤 7: 修补所有语言文件
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "汉化语言文件"
    
    print_info "正在更新 locales 目录下的所有语言文件..."
    
    # 定义中文翻译内容
    LOCALES_CONTENT='create-id-occupied = 房间 ID 已被占用

join-game-ongoing = 游戏正在进行中
join-room-full = 房间已满
join-room-locked = 房间已锁定
join-cant-monitor = 权限不足，不能旁观房间

start-no-chart-selected = 还没有选择谱面

http-not-found = 未找到
http-internal-error = 服务器内部错误

bad-enabled = 缺少 enabled 参数
auth-unauthorized = 未授权
token-expired = 令牌已过期
admin-disabled = 管理员功能未启用
otp-disabled-when-token-configured = 已配置管理员令牌，OTP 功能已禁用
bad-request = 请求参数错误
invalid-or-expired-session = 会话无效或已过期
ip-mismatch = IP 地址不匹配
pending-approval = 等待管理员批准
approval-denied = 提权申请已被拒绝
token-not-issued = 令牌未签发
ip-banned-too-many-attempts = 该 IP 因尝试次数过多已被封禁
ssid-banned-too-many-attempts = 该会话因尝试次数过多已被封禁
invalid-or-expired-otp = 验证码无效或已过期
bad-token = 令牌不能为空
upload-failed = 上传失败
share-station-not-configured = 分享站未配置
upload-success = 上传成功
user-must-be-disconnected = 用户必须处于离线状态
user-not-in-room = 用户不在房间中
cannot-move-while-playing = 游戏进行中无法移动用户
target-room-not-idle = 目标房间不处于空闲状态

cli-invalid-port = 端口号不合法
cli-invalid-http-service = HTTP_SERVICE 不合法
cli-invalid-http-port = HTTP 端口号不合法
cli-invalid-room-max-users = ROOM_MAX_USERS 不合法
cli-invalid-monitors = MONITORS 不合法

label-monitor-suffix = （观战者）
replay-recorder-name = 回放录制器

chat-welcome = "{ $userName }"你好！欢迎来到 { $serverName } 服务器！
chat-welcome-version = 服务器当前版本： { $version } 
chat-hitokoto = { $quote } —— { $from }
chat-hitokoto-from-unknown = 佚名
chat-roomlist-title = 当前可用的房间如下：
chat-roomlist-empty = 当前没有可用房间
chat-roomlist-item = { $id }（{ $count }/{ $max }）
chat-disabled-by-server = 为避免安全问题，该服务器已禁用聊天

chat-game-summary =
    本局结算：
    { $scoreText }
    { $accText }
    { $stdText }
chat-game-summary-score = 最高分："{ $name } "({ $id }) { $score }
chat-game-summary-acc = 最高准度："{ $name } "({ $id }) { $acc }
chat-game-summary-std = 最佳无瑕度："{ $name } "({ $id }) { $std }ms

auth-invalid-token = token 不合法
auth-fetch-me-failed = 获取用户信息失败
auth-failed = 认证失败
auth-invalid-response = 认证响应无效
auth-invalid-user-id = 认证响应中用户ID无效
auth-invalid-user-name = 认证响应中用户名无效
auth-repeated-authenticate = 重复认证
user-banned-by-server = 你已被服务器封禁，无法进行任何操作。

room-already-in-room = 已在房间中
room-creation-disabled = 房间创建功能已被管理员禁用
room-not-found = 房间不存在
room-no-room = 你不在房间中
room-banned = 你已被禁止进入房间 { $id }
room-not-whitelisted = 你不在该房间白名单中
room-only-host = 只有房主可以执行此操作
room-invalid-state = 房间状态不允许此操作
room-already-ready = 已准备
room-not-ready = 未准备
room-game-aborted = 对局已中止

record-invalid = 记录不合法
record-already-uploaded = 已上传记录
record-fetch-failed = 获取记录失败

chart-fetch-failed = 获取谱面失败

net-connection-closed = 连接已关闭
net-send-timeout = 发送超时
net-unsupported-protocol-version = 不支持的协议版本：{ $version }

roomid-empty = 房间 ID 不能为空
roomid-too-long = 房间 ID 过长
roomid-invalid = 房间 ID 不合法

frame-invalid-length = 长度不合法
frame-invalid-length-prefix = 长度前缀不合法
frame-payload-too-large = 数据包过大

binary-unexpected-eof = 意外的 EOF
binary-length-too-large = 长度过大
binary-string-too-long = 字符串过长

proto-roomstate-tag-invalid = RoomState 标签不合法
proto-users-key-missing = users 键不存在
proto-message-tag-invalid = Message 标签不合法
proto-clientcommand-tag-invalid = ClientCommand 标签不合法
proto-servercommand-tag-invalid = ServerCommand 标签不合法

client-not-connected = 未连接
client-ping-in-flight = 上一次 ping 尚未完成
client-heartbeat-timeout = 心跳超时
client-timeout = 超时

log-new-connection = 收到新连接，连接ID：{ $id }，来源：{ $remote }
log-handshake-ok = 连接握手完成，连接ID：{ $id }，协议版本："{ $version }"
log-handshake-failed = 连接握手失败，连接ID：{ $id }：{ $reason }

log-server-version = 服务端版本 { $version }
log-runtime-env = 当前运行环境 { $platform } node{ $node }
log-server-listen = 服务端运行在 { $addr }
log-http-listen = HTTP 服务运行在 { $addr }
log-server-name = 服务器名称 { $name }
log-server-stopped = 服务端已停止

log-heartbeat-timeout-disconnect = 心跳超时，准备断开连接（连接ID：{ $id }）
log-auth-ok = 连接ID：{ $id }，" { $user } " { $monitorSuffix } 认证成功，协议版本："{ $version }"
log-auth-failed = 连接ID：{ $id } 认证失败：{ $reason }

log-player-join = "{ $user }({ $id })"{ $monitorSuffix } 加入了服务器

log-disconnect = 连接断开，连接ID：{ $id } { $who }
log-disconnect-user = ，"{ $user }"

log-user-disconnect-playing = "{ $user }" 对局中断线，强制退出房间 "{ $room }"
log-room-recycled = 房间 "{ $room }" 已回收（无玩家）
log-user-dangle = "{ $user }" 断线，进入挂起等待重连
log-user-dangle-timeout-remove = "{ $user }" 挂起超时，移除用户并退出房间 "{ $room }"

log-user-chat = "{ $user }" 在房间 "{ $room }" 发送聊天消息
log-user-touches = "{ $user }" 在房间 "{ $room }" 上报触控帧 { $count } 条
log-user-judges = "{ $user }" 在房间 "{ $room }" 上报判定事件 { $count } 条

log-room-created = "{ $user }" 创建房间 "{ $room }"
log-room-joined = "{ $user }"{ $suffix } 加入房间 "{ $room }"
log-room-left = "{ $user }"{ $suffix } 离开房间 "{ $room }"

log-msg-create-room = { $user } 创建了房间
log-msg-join-room = { $name } 加入了房间
log-msg-leave-room = { $name } 离开了房间
log-msg-new-host = { $user } 成为了新的房主
log-msg-select-chart = 房主 { $user } 选择了谱面 { $name } (#{ $id })
log-msg-game-start = 房主 { $user } 开始了游戏，请其他玩家准备
log-msg-ready = { $user } 已就绪
log-msg-cancel-ready = { $user } 取消了准备
log-msg-cancel-game = { $user } 取消了对局
log-msg-start-playing = 游戏开始
log-msg-played = { $user } 结束了游玩：{ $score } ({ $acc }%){ $fc ->
    [true] ，全连
   *[false] {""}
}
log-msg-game-end = 游戏结束
log-msg-abort = { $user } 放弃了游戏
log-msg-lock-room = { $lock ->
    [true] 房间已锁定
   *[false] 房间已解锁
}
log-msg-cycle-room = { $cycle ->
    [true] 房间已切换为循环模式
   *[false] 房间已切换为普通模式
}

log-room-lock = "{ $user }" 将房间 "{ $room }"{ $lock ->
    [true] 设为锁定
   *[false] 取消锁定
  }

log-room-cycle = "{ $user }" 将房间 "{ $room }"{ $cycle ->
    [true] 开启轮转房主
   *[false] 关闭轮转房主
  }

log-room-select-chart = "{ $user }"（用户ID：{ $userId }）在房间 "{ $room }" 选择了 "{ $chart }"
log-room-request-start = "{ $user }" 在房间 "{ $room }" 请求开始对局
log-room-ready = "{ $user }" 在房间 "{ $room }" 已准备
log-room-cancel-game = "{ $user }" 在房间 "{ $room }" 取消了对局
log-room-cancel-ready = "{ $user }" 在房间 "{ $room }" 取消准备
log-room-played = "{ $user }" 在房间 "{ $room }" 完成游玩并上传记录（分数：{ $score }，Acc：{ $acc }）
log-room-abort = "{ $user }" 在房间 "{ $room }" 中止了对局

log-room-host-changed-offline = 房间 "{ $room }" 房主变更（离线）：{ $old } -> { $next }
log-room-game-start = 房间 "{ $room }" 对局开始，玩家：{ $users }{ $monitorsSuffix }
log-room-game-start-monitors = ，观战者：{ $monitors }
log-room-game-end = 房间 "{ $room }" 对局结束（已上传：{ $uploaded }，中止：{ $aborted }）
log-contest-game-results = 比赛房间 "{ $room }" 成绩：chart={ $chart } results={ $results } aborted={ $aborted }
log-room-host-changed-cycle = 房间 "{ $room }" 房主变更（轮转）：{ $old } -> { $next }

log-admin-broadcast = 管理员全服广播：{ $message }（发送到 { $rooms } 个房间）
log-admin-room-message = 管理员向房间 "{ $room }" 发送消息：{ $message }
log-room-disbanded-by-admin = 房间 "{ $room }" 已被管理员解散

room-disbanded-by-admin = 房间已被管理员解散

log-websocket-connected = WebSocket 客户端已连接，当前连接数：{ $total }
log-websocket-disconnected = WebSocket 客户端已断开，当前连接数：{ $total }

cli-bad-user-id = 无效的用户ID
cli-bad-room-id = 无效的房间ID
cli-message-empty = 消息不能为空
cli-message-too-long = 消息过长（最多 { $max } 字符）

cli-stop-hint = 使用 Ctrl+C 停止服务器
cli-unknown-command = 未知命令：{ $cmd }。输入 '\''help'\'' 查看可用命令
cli-command-failed = 命令执行失败：{ $reason }

cli-help =

    === Phira MP 服务器命令 ===
    help                          - 显示此帮助信息
    list, rooms                   - 列出所有房间
    users                         - 列出所有在线用户
    user <id>                     - 查看用户信息
    kick <userId> [preserve]      - 踢出用户（preserve=true 保留房间槽位）
    ban <userId>                  - 在服务器封禁用户
    unban <userId>                - 解封用户
    banlist                       - 查看封禁列表
    banroom <userId> <roomId>     - 禁止用户进入房间
    unbanroom <userId> <roomId>   - 解除房间禁入
    broadcast <message>           - 全服广播
    say <message>                 - 全服广播（broadcast 别名）
    roomsay <roomId> <message>    - 向指定房间发送消息
    maxusers <roomId> <count>     - 设置房间最大人数
    disband <roomId>              - 解散房间
    replay <on|off|status>        - 回放录制开关
    roomcreation <on|off|status>  - 房间创建开关
    contest <roomId> <subcommand> - 比赛房间管理
      contest <roomId> enable [userIds...]    - 启用比赛模式
      contest <roomId> disable                - 禁用比赛模式
      contest <roomId> whitelist <userIds...> - 设置白名单
      contest <roomId> start [force]          - 手动开始比赛
    ipblacklist <list|remove|clear> - IP 黑名单管理
    pending                       - 列出所有待处理的 CLI 提权申请
    approve <ssid>                - 批准 CLI 提权申请并签发临时 TOKEN（支持 ssid 前缀短码）
    deny <ssid>                   - 拒绝 CLI 提权申请（支持 ssid 前缀短码）

cli-no-rooms = 当前没有房间
cli-rooms-total = 房间总数：{ $count }
cli-room-line = [{ $id }] { $state } | 玩家：{ $users }/{ $maxUsers } | 观战：{ $monitors } | 谱面：{ $chart } | 锁定：{ $locked } | 循环：{ $cycle } | 比赛：{ $contest }

cli-no-users = 当前没有在线用户
cli-users-total = 在线用户总数：{ $count }
cli-user-line = [{ $id }] { $name } | { $status } | { $role } | 房间：{ $room }{ $bannedTag }
cli-user-status-online = 在线
cli-user-status-offline = 离线
cli-user-role-monitor = 观战
cli-user-role-player = 玩家
cli-user-banned-tag =  [已封禁]
cli-none = 无
cli-yes = 是
cli-no = 否
cli-state-on = 开启
cli-state-off = 关闭
cli-room-state-playing = 游戏中
cli-room-state-waiting = 等待准备
cli-room-state-select = 选择谱面
cli-bool-yes = 是
cli-bool-no = 否

cli-usage-user = 用法：user <userId>
cli-usage-kick = 用法：kick <userId> [preserve]
cli-usage-ban = 用法：ban <userId>
cli-usage-unban = 用法：unban <userId>
cli-usage-banroom = 用法：banroom <userId> <roomId>
cli-usage-unbanroom = 用法：unbanroom <userId> <roomId>
cli-usage-broadcast = 用法：broadcast <message>
cli-usage-roomsay = 用法：roomsay <roomId> <message>
cli-usage-maxusers = 用法：maxusers <roomId> <count>
cli-usage-disband = 用法：disband <roomId>
cli-usage-replay = 用法：replay <on|off|status>
cli-usage-roomcreation = 用法：roomcreation <on|off|status>
cli-usage-contest = 用法：contest <roomId> <enable|disable|whitelist|start>
cli-usage-ipblacklist = 用法：ipblacklist <list|remove|clear>
cli-usage-ipblacklist-remove = 用法：ipblacklist remove <ip>

cli-user-not-found = 用户不存在：{ $id }
cli-user-info-header = 用户信息：
cli-user-info-id =   ID：{ $id }
cli-user-info-name =   名称：{ $name }
cli-user-info-status =   状态：{ $status }
cli-user-info-role =   角色：{ $role }
cli-user-info-room =   房间：{ $room }
cli-user-info-banned =   封禁：{ $banned }
cli-user-info-game-time =   游戏时间：{ $time }
cli-user-info-language =   语言：{ $lang }

cli-user-not-connected = 用户未连接：{ $id }
cli-user-kicked = 已踢出用户：{ $id }
cli-user-banned = 已封禁用户：{ $id }
cli-user-unbanned = 已解封用户：{ $id }
cli-no-banned-users = 当前没有被封禁的用户
cli-banned-list-header = 封禁用户列表（共 { $count } 个）：
cli-room-user-banned = 已禁止用户 { $userId } 进入房间 { $room }
cli-room-user-unbanned = 已解除用户 { $userId } 对房间 { $room } 的禁入
cli-broadcast-sent = 已向 { $count } 个房间广播消息
cli-room-not-found = 房间不存在
cli-room-not-found-named = 房间不存在：{ $room }
cli-room-message-sent = 已向房间 { $room } 发送消息
cli-bad-max-users = 无效的人数（1-64）
cli-room-max-users-set = 已设置房间 { $room } 最大人数为 { $count }
cli-room-disbanded = 已解散房间 { $room }

cli-replay-status = 回放录制状态：{ $state }
cli-replay-toggled-on = 回放录制已开启
cli-replay-toggled-off = 回放录制已关闭
cli-room-creation-status = 房间创建状态：{ $state }
cli-room-creation-toggled-on = 房间创建已开启
cli-room-creation-toggled-off = 房间创建已关闭

cli-contest-enabled = 已启用房间 { $room } 的比赛模式
cli-contest-disabled = 已禁用房间 { $room } 的比赛模式
cli-contest-no-user-id = 请提供至少一个用户ID
cli-contest-not-enabled = 房间不存在或未启用比赛模式
cli-contest-whitelist-updated = 已更新房间 { $room } 的白名单
contest-room-not-found = 比赛房间不存在
room-not-waiting = 房间不在等待准备状态
no-chart-selected = 未选择谱面
not-all-ready = 并非所有玩家都已准备
cli-contest-cannot-start = 无法开始比赛：{ $reason }
cli-contest-started = 已开始房间 { $room } 的比赛
cli-contest-unknown-subcommand = 未知子命令。可用：enable、disable、whitelist、start

cli-blacklist-empty = IP 黑名单为空
cli-blacklist-header = IP 黑名单（共 { $count } 个）：
cli-blacklist-line =   { $ip }（{ $minutes } 分钟后过期）
cli-blacklist-removed = 已从黑名单移除：{ $ip }
cli-blacklist-cleared = 已清空 IP 黑名单
cli-ipblacklist-unknown-subcommand = 未知子命令。可用：list、remove、clear

cli-usage-approve = 用法：approve <ssid>（支持完整 ssid 或前缀短码）
cli-usage-deny = 用法：deny <ssid>（支持完整 ssid 或前缀短码）
cli-approve-not-found = 未找到匹配的提权申请：{ $input }
cli-approve-ambiguous = 短码 { $input } 匹配到多个提权申请，请提供更长的前缀
cli-approve-expired = 提权申请 { $ssid } 已过期
cli-approve-already-handled = 提权申请 { $ssid } 已处于 { $status } 状态，无法再次处理
cli-approve-success = 已批准提权申请 { $ssid }（请求IP：{ $ip }），临时 TOKEN 已签发
cli-deny-success = 已拒绝提权申请 { $ssid }（请求IP：{ $ip }）
cli-pending-empty = 当前没有待处理的 CLI 提权申请
cli-pending-header = 待处理的 CLI 提权申请（共 { $count } 个）：
cli-pending-line =   [{ $ssid }] 完整 ssid: { $full } | 请求IP: { $ip } | 剩余 { $seconds } 秒'

    # 写入所有语言文件
    for lang in en-US zh-CN zh-TW ja-JP ko-KR ru-RU; do
        echo "$LOCALES_CONTENT" > "locales/${lang}.ftl"
        echo -e "   ${GREEN}✓${NC} locales/${lang}.ftl 已更新"
    done
    
    echo ""
    print_success "所有语言文件已汉化完成"
    sleep 1
    
    # ==================================================
    # 步骤 8: 配置 .bashrc 自动启动
    # ==================================================
    CURRENT_STEP=$((CURRENT_STEP + 1))
    show_progress $CURRENT_STEP $TOTAL_STEPS "配置 .bashrc 自动启动"
    
    print_info "正在写入自动启动逻辑到 .bashrc..."
    echo ""
    
    # 直接配置 .bashrc（不生成中间脚本，只使用 GitHub 直连）
    configure_bashrc
    
    echo ""
    print_success ".bashrc 自动启动配置完成"
    sleep 0.5
    
    # ==================================================
    # 安装完成
    # ==================================================
    clear
    echo -e "${GREEN}"
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                                                              ║"
    echo "║                    🎉  安装成功！ 🎉                         ║"
    echo "║                                                              ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    echo -e "${GREEN}  Phira MP 联机服务器已安装完成！${NC}"
    echo ""
    echo -e "${CYAN}  下次打开 Termux 时将自动检测并启动！${NC}"
    echo ""
}

# 错误处理
trap 'echo ""; print_error "安装过程中出现错误，请检查上面的输出信息"; exit 1' ERR

# 启动主程序
main
